### ISSUE TITLE
パイプ使うと動いた後tokenizerが死ぬ

### ISSUE THREAD

**Issue by Wolframike** [Wolframike/minishell#21]
(追記)よく考えたらparserで使う構造体消しきれてないからな気がして来た
(追記)そうじゃない気がしてきた

コマンドがビルトインであるでない関わらず出る
俺側の問題な気がする

```
MINISHELL>> echo this is a test | cat -e
this is a test$
MINISHELL>> AddressSanitizer:DEADLYSIGNAL
=================================================================
==90068==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x00010b3f9bbe bp 0x7ffee4807670 sp 0x7ffee4807480 T0)
==90068==The signal is caused by a READ memory access.
==90068==Hint: address points to the zero page.
    #0 0x10b3f9bbd in tokenize (minishell:x86_64+0x100001bbd)
    #1 0x10b3fb482 in parse (minishell:x86_64+0x100003482)
    #2 0x10b3f9749 in main (minishell:x86_64+0x100001749)
    #3 0x7fff5a4023d4 in start (libdyld.dylib:x86_64+0x163d4)
```

複数回入力をもらいに行かなければ死なないので俺がfd荒らしてしまってるせい説もある

```
MINISHELL>> echo this is a test | cat -e
this is a test$
minishell|execute-ast-tree⚡ ⇒
```

**Comment by Wolframike** [comment]
気づいたら死ななくなってたからいいです

**Comment by Wolframike** [comment]
気づいたら死ななくなってました
