### ISSUE TITLE
連続エンターで時々死ぬ

### ISSUE THREAD

**Issue by Wolframike** [Wolframike/minishell#22]
```bash
MINISHELL>> pwd
/Users/misargsy/42cursus/minishell
MINISHELL>>
MINISHELL>>
MINISHELL>> pwd
/Users/misargsy/42cursus/minishell
MINISHELL>>
AddressSanitizer:DEADLYSIGNAL
=================================================================
==29457==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x000101bdcbe8 bp 0x7ffeee037dc0 sp 0x7ffeee037d90 T0)
==29457==The signal is caused by a READ memory access.
==29457==Hint: address points to the zero page.

    #0 0x101bdcbe7 in __asan::Allocator::Deallocate(void*, unsigned long, unsigned long, __sanitizer::BufferedStackTrace*, __asan::AllocType) (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x3be7)
    #1 0x101c3aa11 in wrap_free (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x61a11)
    #2 0x101bcc1ad in destroy_token (minishell:x86_64+0x1000051ad)
    #3 0x101bca5a5 in parse (minishell:x86_64+0x1000035a5)
    #4 0x101bc8789 in main (minishell:x86_64+0x100001789)
    #5 0x7fff7764e3d4 in start (libdyld.dylib:x86_64+0x163d4)
```

**Comment by Wolframike** [comment]
```
MINISHELL>> ls
Makefile	infile		libft.a		srcs
includes	libft		minishell	valgrind.logs
MINISHELL>>
AddressSanitizer:DEADLYSIGNAL
=================================================================
==31516==ERROR: AddressSanitizer: SEGV on unknown address 0x0000e8bb16a8 (pc 0x000107051805 bp 0x7ffee8bb1670 sp 0x7ffee8bb1540 T0)
==31516==The signal is caused by a READ memory access.

    #0 0x107051804 in parse_and_or (minishell:x86_64+0x100003804)
    #1 0x10705155e in parse (minishell:x86_64+0x10000355e)
    #2 0x10704f789 in main (minishell:x86_64+0x100001789)
    #3 0x7fff7764e3d4 in start (libdyld.dylib:x86_64+0x163d4)
```

**Comment by Wolframike** [comment]
なおってたw
